server:
  http:
    address: ":8080"
database:
  dsn: ""
log:
  level: info
s3:
  endpoint: "http://localhost:9000"
  region: us-east-1
  bucket: avatars
  access_key: your-access-key
  secret_key: your-secret-key
  path_style: true
rabbitmq:
  url: amqp://user:password@localhost:5672/
