server:
  http:
    address: ":8080"
database:
  dsn: ""
log:
  level: info
s3:
  endpoint: "http://localhost:9000"
  region: us-east-1
  bucket: avatars
  access_key: minio
  secret_key: minio12345
  path_style: true
rabbitmq:
  url: amqp://avatars:avatars@localhost:5672/