// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/Radiushina/avatar-service/cmd/server/di/providers"
	"github.com/Radiushina/avatar-service/internal/domains/avatars"
)

// Injectors from wire.go:

// InjectApp uses Wire to construct the application with all dependencies.
// This function is implemented by Wire during code generation (wire_gen.go).
// It returns the initialized App, a cleanup function, and any initialization errors.
func InjectApp(ctx context.Context) (*App, func(), error) {
	config, err := providers.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := providers.NewLogger(config)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup2, err := providers.NewPostgres(ctx, config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repo := avatars.NewAvatarRepo(pool)
	service := avatars.NewService(repo)
	server := providers.NewHTTPServer(config, service)
	servers := providers.NewServers(server, logger)
	app := &App{
		cfg:    config,
		server: servers,
		Log:    logger,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
